import type { Metadata } from "next";

// metadata
export const metadata: Metadata = {
	title: "New Bunext",
	description: "Generated by create next app",
};
// css
import "@/styles/globals.css";
// utilities
import { cn } from "@/lib/utils";
import { fonts } from "@/styles/fonts";
// providers
import { RootProvider } from "@/components/providers/root-provider";
// components
import { ModeToggle } from "@/components/ModeToggle";

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={cn("font-sans antialiased", fonts)}>
				<RootProvider>
					{children}
					<ModeToggle
						className="fixed bottom-3 left-3 z-50"
						iconClassName="size-[11px]"
					/>
				</RootProvider>
			</body>
		</html>
	);
}
