import type { Metadata } from "next";

// metadata
export const metadata: Metadata = {
	title: "New Bunext",
	description: "Generated by create next app",
};
// css
import "@/styles/globals.css";
// utilities
import { cn } from "@/lib/utils";
import { fonts } from "@/styles/fonts";
// providers
import { RootProvider } from "@/components/providers/root-provider";
// components
import { ModeToggle } from "@/components/ModeToggle";
import { FeatureFlag } from "@/components/utils/featureFlag";

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={cn("font-sans", fonts)}>
				<RootProvider>
					{children}

					{/* checks if theme and theme button feature flags are enabled */}
					<FeatureFlag featureFlag={["NEXT_THEME", "THEME_BUTTON"]}>
						<ModeToggle
							className="fixed bottom-3 left-3 z-50"
							iconClassName="size-[11px]"
						/>
					</FeatureFlag>
				</RootProvider>
			</body>
		</html>
	);
}
